
services:
  zookeeper:
    image: bitnami/zookeeper:latest

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
      - kafka
      - mongodb
      - elasticsearch

  mongodb:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"



  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: my_elastic
    ports:
      - "9200:9200"




